// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: fm_data.proto

package go_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FmDataService_GetFmItems_FullMethodName = "/fmdata_proto.FmDataService/GetFmItems"
	FmDataService_GetFmItem_FullMethodName  = "/fmdata_proto.FmDataService/GetFmItem"
)

// FmDataServiceClient is the client API for FmDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FmDataServiceClient interface {
	GetFmItems(ctx context.Context, in *FmDataRequest, opts ...grpc.CallOption) (*FmData, error)
	GetFmItem(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*Item, error)
}

type fmDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFmDataServiceClient(cc grpc.ClientConnInterface) FmDataServiceClient {
	return &fmDataServiceClient{cc}
}

func (c *fmDataServiceClient) GetFmItems(ctx context.Context, in *FmDataRequest, opts ...grpc.CallOption) (*FmData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FmData)
	err := c.cc.Invoke(ctx, FmDataService_GetFmItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fmDataServiceClient) GetFmItem(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, FmDataService_GetFmItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FmDataServiceServer is the server API for FmDataService service.
// All implementations must embed UnimplementedFmDataServiceServer
// for forward compatibility.
type FmDataServiceServer interface {
	GetFmItems(context.Context, *FmDataRequest) (*FmData, error)
	GetFmItem(context.Context, *ItemRequest) (*Item, error)
	mustEmbedUnimplementedFmDataServiceServer()
}

// UnimplementedFmDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFmDataServiceServer struct{}

func (UnimplementedFmDataServiceServer) GetFmItems(context.Context, *FmDataRequest) (*FmData, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFmItems not implemented")
}
func (UnimplementedFmDataServiceServer) GetFmItem(context.Context, *ItemRequest) (*Item, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFmItem not implemented")
}
func (UnimplementedFmDataServiceServer) mustEmbedUnimplementedFmDataServiceServer() {}
func (UnimplementedFmDataServiceServer) testEmbeddedByValue()                       {}

// UnsafeFmDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FmDataServiceServer will
// result in compilation errors.
type UnsafeFmDataServiceServer interface {
	mustEmbedUnimplementedFmDataServiceServer()
}

func RegisterFmDataServiceServer(s grpc.ServiceRegistrar, srv FmDataServiceServer) {
	// If the following call panics, it indicates UnimplementedFmDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FmDataService_ServiceDesc, srv)
}

func _FmDataService_GetFmItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FmDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FmDataServiceServer).GetFmItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FmDataService_GetFmItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FmDataServiceServer).GetFmItems(ctx, req.(*FmDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FmDataService_GetFmItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FmDataServiceServer).GetFmItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FmDataService_GetFmItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FmDataServiceServer).GetFmItem(ctx, req.(*ItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FmDataService_ServiceDesc is the grpc.ServiceDesc for FmDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FmDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fmdata_proto.FmDataService",
	HandlerType: (*FmDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFmItems",
			Handler:    _FmDataService_GetFmItems_Handler,
		},
		{
			MethodName: "GetFmItem",
			Handler:    _FmDataService_GetFmItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fm_data.proto",
}
