// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: fm_data.proto

package go_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FmDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FmDataRequest) Reset() {
	*x = FmDataRequest{}
	mi := &file_fm_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FmDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FmDataRequest) ProtoMessage() {}

func (x *FmDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fm_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FmDataRequest.ProtoReflect.Descriptor instead.
func (*FmDataRequest) Descriptor() ([]byte, []int) {
	return file_fm_data_proto_rawDescGZIP(), []int{0}
}

func (x *FmDataRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *FmDataRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRequest) Reset() {
	*x = ItemRequest{}
	mi := &file_fm_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRequest) ProtoMessage() {}

func (x *ItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fm_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRequest.ProtoReflect.Descriptor instead.
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return file_fm_data_proto_rawDescGZIP(), []int{1}
}

func (x *ItemRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *ItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Nummer        string                 `protobuf:"bytes,3,opt,name=nummer,proto3" json:"nummer,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Parent        string                 `protobuf:"bytes,6,opt,name=parent,proto3" json:"parent,omitempty"`
	ParentType    string                 `protobuf:"bytes,7,opt,name=parent_type,json=parentType,proto3" json:"parent_type,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_fm_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_fm_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_fm_data_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Item) GetNummer() string {
	if x != nil {
		return x.Nummer
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *Item) GetParentType() string {
	if x != nil {
		return x.ParentType
	}
	return ""
}

func (x *Item) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type FmData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FmData) Reset() {
	*x = FmData{}
	mi := &file_fm_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FmData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FmData) ProtoMessage() {}

func (x *FmData) ProtoReflect() protoreflect.Message {
	mi := &file_fm_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FmData.ProtoReflect.Descriptor instead.
func (*FmData) Descriptor() ([]byte, []int) {
	return file_fm_data_proto_rawDescGZIP(), []int{3}
}

func (x *FmData) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_fm_data_proto protoreflect.FileDescriptor

const file_fm_data_proto_rawDesc = "" +
	"\n" +
	"\rfm_data.proto\x12\ffmdata_proto\"=\n" +
	"\rFmDataRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"K\n" +
	"\vItemRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xc9\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06nummer\x18\x03 \x01(\tR\x06nummer\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06parent\x18\x06 \x01(\tR\x06parent\x12\x1f\n" +
	"\vparent_type\x18\a \x01(\tR\n" +
	"parentType\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\"2\n" +
	"\x06FmData\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.fmdata_proto.ItemR\x05items2\x90\x01\n" +
	"\rFmDataService\x12A\n" +
	"\n" +
	"GetFmItems\x12\x1b.fmdata_proto.FmDataRequest\x1a\x14.fmdata_proto.FmData\"\x00\x12<\n" +
	"\tGetFmItem\x12\x19.fmdata_proto.ItemRequest\x1a\x12.fmdata_proto.Item\"\x00B'Z%github.com/christian-schueler/go-grpcb\x06proto3"

var (
	file_fm_data_proto_rawDescOnce sync.Once
	file_fm_data_proto_rawDescData []byte
)

func file_fm_data_proto_rawDescGZIP() []byte {
	file_fm_data_proto_rawDescOnce.Do(func() {
		file_fm_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fm_data_proto_rawDesc), len(file_fm_data_proto_rawDesc)))
	})
	return file_fm_data_proto_rawDescData
}

var file_fm_data_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fm_data_proto_goTypes = []any{
	(*FmDataRequest)(nil), // 0: fmdata_proto.FmDataRequest
	(*ItemRequest)(nil),   // 1: fmdata_proto.ItemRequest
	(*Item)(nil),          // 2: fmdata_proto.Item
	(*FmData)(nil),        // 3: fmdata_proto.FmData
}
var file_fm_data_proto_depIdxs = []int32{
	2, // 0: fmdata_proto.FmData.items:type_name -> fmdata_proto.Item
	0, // 1: fmdata_proto.FmDataService.GetFmItems:input_type -> fmdata_proto.FmDataRequest
	1, // 2: fmdata_proto.FmDataService.GetFmItem:input_type -> fmdata_proto.ItemRequest
	3, // 3: fmdata_proto.FmDataService.GetFmItems:output_type -> fmdata_proto.FmData
	2, // 4: fmdata_proto.FmDataService.GetFmItem:output_type -> fmdata_proto.Item
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fm_data_proto_init() }
func file_fm_data_proto_init() {
	if File_fm_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fm_data_proto_rawDesc), len(file_fm_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fm_data_proto_goTypes,
		DependencyIndexes: file_fm_data_proto_depIdxs,
		MessageInfos:      file_fm_data_proto_msgTypes,
	}.Build()
	File_fm_data_proto = out.File
	file_fm_data_proto_goTypes = nil
	file_fm_data_proto_depIdxs = nil
}
